name: Github Actions Demo

on:
  push:
    branches: [ main ]
    paths-ignore: [.github/**]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '15 6 * * 0'
  workflow_dispatch: 

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "El job fue lanzado por el evento: ${{ github.event_name }}"
          echo "El nombre de la rama es: ${{ github.ref }} y tu repositorio es ."

      - uses: actions/checkout@v3.3.0

      - name: Listado de archivos en el repositorio
        run: |
          echo "El repositorio ${{ github.repository }} contains los siguientes archivos:"
          tree
